project:
  type: website
  output-dir: docs
  preview:
    port: 4385

website:
  title: "Spatial Data Analysis"
  sidebar:
    background: primary
    logo: "images/esda.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sjsrey/385s23
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
        
format:
  html:
    theme: cosmo
   # css: styles.css
    toc: true



