project:
  type: website

website:
  title: "Spatial Data Analysis"
  sidebar:
    background: primary
    logo: "images/esda.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/rstudio-conf-2022/teach-ds-course-website
        text: GitHub
      - icon: cloud-fill
        href: https://rstudio.cloud/spaces/237799
        text: RStudio Cloud
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
        
format:
  html:
    theme: cosmo
   # css: styles.css
    toc: true



